# Generated by Django 2.2.2 on 2019-07-03 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(choices=[(1, 'ubrania, które nadają się do ponownego użycia'), (2, 'ubrania do wyrzucenia'), (3, 'zabawki'), (4, 'książki'), (5, 'inne')])),
                ('bags', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.IntegerField(choices=[(1, 'dolnośląskie'), (2, 'kujawsko-pomorskie'), (3, 'lubelskie'), (4, 'lubuskie'), (5, 'łódzkie'), (6, 'małopolskie'), (7, 'mazowieckie'), (8, 'opolskie'), (9, 'podkarpackie'), (10, 'podlaskie'), (11, 'pomorskie'), (12, 'śląskie'), (13, 'świętokrzyskie'), (14, 'warmińsko-mazurskie'), (15, 'wielkopolskie'), (16, 'zachodniopomorskie')])),
                ('beneficiary', models.IntegerField(choices=[(1, 'dzieciom'), (2, 'samotnym matkom'), (3, 'bezdomnym'), (4, 'niepełnosprawnym'), (5, 'osobom starszym'), (6, 'bezrobotnym')])),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('post_code', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('info', models.TextField(blank=True)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Items')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Organization')),
            ],
        ),
    ]
